### ISSUE TITLE
Track command output of generated projects via shared lane context

### ISSUE THREAD

**Issue by liamnichols** [NovatecConsulting/fastlane-plugin-xcodegen#4]
In our workspace, we generate multiple different projects and as a result, we invoke the `xcodegen` command/action three times:

```ruby
lane :setup_workspace do
  xcodegen(spec: 'Frameworks/project.yml', use_cache: true)
  xcodegen(spec: 'App/project.yml, 'use_cache: true)
  cocoapods
  ensure_git_status_clean if is_ci?
end
```

While we leverage `use_cache` to avoid generating projects when its not required, we also want to know if any of the Xcode projects changed before we go ahead and run other actions such as `cocoapods`. 

XcodeGen offers a `postGenCommand` option that only runs if the project was actually generated (and not skipped due to no changes) however we can't directly run `pod install` there since we need to wait until we know the status of **all** the projects.

I guess this is probably quite a unique use case, but I think the best way to support this kind of use case in the action would be to hold the command output for each invocation in the [Lane Context](https://docs.fastlane.tools/advanced/lanes/#lane-context) where a hash is keyed by the `:spec` that is passed in.

For example:

```ruby
spec = params[:spec] || 'project.yml' # project.yml is XcodeGen's default if the argument isn't specified

cmd = ["xcodegen"]
cmd << "--spec #{spec}"
cmd << "--project #{params[:project]}" if params[:project]
cmd << "--quiet" if params[:quiet]
cmd << "--use-cache" if params[:use_cache]
cmd << "--cache-path #{params[:cache_path]}" if params[:cache_path]
cmd << "--project-root #{params[:project_root]}" if params[:project_root]

output = Actions.sh(cmd.join(' '))

outputs = Actions.lane_context[SharedValues::XCODEGEN_OUTPUTS] || {}
outputs[spec] = output
Actions.lane_context[SharedValues::XCODEGEN_OUTPUTS] = outputs
```

Users of the action could then use the `XCODEGEN_OUTPUTS` hash to work out if any of the projects actually ended up being generated. In my specific setup, I have a `postGenCommand` that echos `PROJECT_GENERATED`, I can then test if any of the outputs contain this string and decide to run `cocoapods`.

So my lane could end up looking like this:

```ruby
lane :setup_workspace do
  xcodegen(spec: 'Frameworks/project.yml', use_cache: true)
  xcodegen(spec: 'App/project.yml, 'use_cache: true)
  
  projects_changed = Actions.lane_context[SharedValues::XCODEGEN_OUTPUTS].any? { |k,v| v.include?("PROJECT_GENERATED") }
  cocoapods if projects_changed
  
  ensure_git_status_clean if is_ci?
end
```

**Comment by m-ruhl** [comment]
Hi 👋 

thanks for the detailed issue.. still needed some time to wrap my head around it.

I don't like the solution with the shared-context. Seams very hacky inside the plugin and to use.

Would it work if you can enter an array of `specs: ['Frameworks/project.yml', 'App/project.yml']` and determine if any project has changed inside the plugin and only return a `boolean`?

**Comment by liamnichols** [comment]
Thanks for the feedback @m-ruhl, I'll admit that I don't think its ideal but I also think that its too much custom behaviour to build inside this plugin directly.

On second thought, I've had a different idea... Currently, the plugin returns the raw output of the shell command anyway. I'm not sure if this was intentional or not, but i'm actually able to solve my problem by dong this:

```ruby
outputs = []
outputs << xcodegen(spec: 'Frameworks/project.yml', use_cache: true)
outputs << xcodegen(spec: 'App/project.yml, 'use_cache: true)

projects_changed = outputs.include?("PROJECT_GENERATED")
cocoapods if projects_changed
```

This is probably actually the easier thing to do 😅 


If you are happy, I'll just submit a PR with a test that ensures that the shell output is the return value of this action? I can also document the `return_type` and `return_value` to explain this (https://github.com/fastlane/fastlane/blob/2720dabcdbf111f9056813ab39b81a989dc5d319/fastlane/lib/fastlane/action.rb#L70-L78). Let me know what you think! Thanks
